### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by rhoegg** [anypointcloud/json-logger#1]
This is a proposal to change the license and publish to maven central similar to the other Anypoint Cloud modules. I am proposing:

- changing the LICENSE file to Apache 2.0
- adding Mathias as a developer in the pom.xml
- Updating the pom.xml with the release configurations needed for maven central release
- Changing the groupId to cloud.anypoint
- Releasing to maven central
- Updating the README to offer users the option of using the maven central version, as well as forking and publishing to their own exchange

**Comment by rhoegg** [comment]
I will be happy to help do some of these steps, as I currently have the publisher rights to maven central cloud.anypoint groupId.

Thoughts @mtransier ?

**Comment by mtransier** [comment]
I like the idea. What I am not sure about is the license update, as I am not a lawyer ;-). Do you have experience with it?

What would be your proposal regarding the deploy script? If we change the groupId, we either have to update the deploy script or remove it completely. Anyhow, it does not provide too much value, a short guide in README could do the same - so we could remove the script.

We could also get rid of the two-level structure. This is something, I usually do for each project where I am using it.

**Comment by mtransier** [comment]
@rhoegg Please have a look at the branch I have opened for these changes and let me know your comments. The release part is still open, I would need your support on that.
