### ISSUE TITLE
Missing Parameter Error in JSON LOGGER when Flowing Logs to AMQP

### ISSUE THREAD

**Issue by Rafael-de-Moura-Brito** [anypointcloud/json-logger#3]
When attempting to flow logs to an AMQP server using the JSON LOGGER, we encounter an error related to a missing parameter called messageBuilder. It's worth noting that all parameters are properly filled in. This issue appears to be a bug caused by the new runtime 4.6.

Even when using the latest version 2.1.0 on runtime 4.6, the issue persists.
```
ERROR 2024-05-02 11:19:45,729 [Thread-12] [processor: ; event: ] org.mule.extension.jsonlogger.internal.destinations.AMQPDestination: Error: Parameter does not exist in any group: messageBuilder
java.lang.IllegalArgumentException: Parameter does not exist in any group: messageBuilder
```

**Comment by mtransier** [comment]
Hi @Rafael-de-Moura-Brito, have you tried the version 2.2.1 from this repository as well?

**Comment by mtransier** [comment]
Hi @Rafael-de-Moura-Brito, I've made a fix that solves it for me locally. Can you please try if it works for you as well?
