### ISSUE TITLE
Json logger code is not forwarding the logs to AMQP (Rabbit MQ) Destination

### ISSUE THREAD

**Issue by gowrisankarvaka** [anypointcloud/json-logger#7]
Raising an error while deployment: 
"Failed to invoke lifecycle phase "initialise" on object: org.mule.extension.jsonlogger.internal.singleton.LogEventSingleton"
"com/lmax/disruptor/util/DaemonThreadFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

**Comment by mtransier** [comment]
55.0 is Java 11, 52.0 is Java 8 --> You are running Java 8 and trying to use a dependency that is compiled for Java 11. I would recommend to use Java 17 for running Mule.
